config/routes.rb
Rails.application.routes.draw do

    resources :characters
    resources :players
    resources :stories
    get '/login'  => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

end

app/models/character.rb
class Character  < ActiveRecord::Base
  belongs_to :player

  validates :name, presence: true
  validates :intel, presence: true
  validates :wits, presence: true
  validates :res, presence: true
  validates :str, presence: true
  validates :dex, presence: true
  validates :stam, presence: true
  validates :cha, presence: true
  validates :manip, presence: true
  validates :academics, presence: true
  validates :computer, presence: true
  validates :crafts, presence: true
  validates :investigation, presence: true
  validates :medicine, presence: true
  validates :occult, presence: true
  validates :politics, presence: true
  validates :science, presence: true
  validates :athletics, presence: true
  validates :brawl, presence: true
  validates :drive, presence: true
  validates :firearms, presence: true
  validates :larceny, presence: true
  validates :stealth, presence: true
  validates :survival, presence: true
  validates :weaponry, presence: true
  validates :animalken, presence: true
  validates :empathy, presence: true
  validates :expression, presence: true
  validates :intimidation, presence: true
  validates :persuasion, presence: true
  validates :socialize, presence: true
  validates :streetwise, presence: true
  validates :subterfuge, presence: true

  validates :meritlist, presence: true
  validates :powerlist, presence: true

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :characters
  has_many :stories
  has_secure_password

  validates :player_name, presence: true
end

app/models/story.rb
class Story  < ActiveRecord::Base
  belongs_to :player

   validates :name, presence: true
   validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_player
    @current_player ||= Player.find(session[:player_id]) if session[:player_id]
  end
  helper_method(:current_player)

  def authorize
    redirect_to '/login' unless current_player
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

    before_action :authorize, except: [:index]

    def index
      @characters = Character.all
    end

    def show
        @character = 'characters/index'
      end

    def new
      @character = Character.new

      id = session[:player_id]
      @player = Player.find(id)

    end

    def create
      character = Character.create(character_params)
      character.player_id = current_player.id
      if character.save
        redirect_to '/characters'
      else
        redirect_to '/characters/new'
      end
    end

    def edit
      @character = Character.find(params[:id])
    end

    def update
      character = Character.find(params[:id])
      if character.update(character_params)
        redirect_to '/characters'
      else
        redirect_to '/characters/edit'
      end
    end

    def destroy
      character = Character.find(params[:id])
      character.destroy
      redirect_to '/characters'
    end

    private

    def character_params
      params.require(:character).permit(
        :name,
        :intel,
        :wits,
        :res,
        :str,
        :dex,
        :stam,
        :cha,
        :manip,
        :Comp,
        :academics,
        :computer,
        :crafts,
        :investigation,
        :medicine,
        :occult,
        :politics,
        :science,
        :athletics,
        :brawl,
        :drive,
        :firearms,
        :larceny,
        :stealth,
        :survival,
        :weaponry,
        :animalken,
        :empathy,
        :expression,
        :intimidation,
        :persuasion,
        :socialize,
        :streetwise,
        :subterfuge,
       :meritlist,
       :powerlist,
       :experience,
              )
    end
  end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

    def index
      @players = Player.all
    end

    def new
      @player = Player.new
    end

    def show
        @player = 'players/index'
      end

      def create
        player = Player.create(player_params)
        if player.save
          redirect_to '/players'
        else
          redirect_to '/players/new'
        end
      end
    private

    def player_params
      params.require(:player).permit(
        :player_name,
        :password,
        :password_confirmation
      )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    player = Player.find_by(player_name: params[:player_name])
    if player && player.authenticate(params[:password])
      session[:player_id] = player.id
      redirect_to "/players"
    else
      redirect_to "/login"
    end
  end
  def destroy
    session[:player_id] = nil
    redirect_to "/login"
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authorize, except: [:index]

    def index
      @Stories = Story.all
    end

    def new
      @post = Story.new

      id = session[:player_id]
      @player = Player.find(id)

    end

    def create
      post = Story.create(post_params)
      post.player_id = current_player.id
      if post.save
        redirect_to '/Stories'
      else
        redirect_to '/Stories/new'
      end
    end

    def edit
      @post = Story.find(params[:id])
    end

    def update
      post = Story.find(params[:id])
      if post.update(post_params)
        redirect_to '/Stories'
      else
        redirect_to '/Stories/edit'
      end
    end

    def destroy
      post = Story.find(params[:id])
      post.destroy
      redirect_to '/Stories'
    end

    private

    def post_params
      params.require(:post).permit(
        :title,
        :body
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Characters/index.html.erb
<h1>characters</h1>

<ul>
  <% @characters.each do |character| %>
  <li>
    <div class="character">
      <h3><%= " #{character.title}"%> </h3>
      <h4><%=" by #{character.player.player_name}" %></h4>
      <p><%= character.body %></p>
      <% if character.player == current_player %>
        <%= link_to "Edit Your character" , edit_character_path(id: character.id) %>
      <% end %>
    </div>
  </li>
  <% end %>
</ul>

app/views/Characters/new.html.erb
<%= form_for @character, url: "/characters" do |f| %>

  Title: <%= f.text_field :title %>
  Body:  <%= f.text_area  :body  %>

  <%= f.submit "I'm DONE!" %>
Congratulations!
<% end %>

app/views/characters/edit.html.erb
<%= form_for @character do |f| %>
/<div class="name">
  NAME <%= f.text_field :name%>
</div>
  <div class="mentalattributes">
    intelligence<%= f.text_field :intel%>
    Wits<%= f.text_field :wits%>
    resolve<%= f.text_field :res%>
    </div>
  <div class="physicalattributes">
    strength<%= f.text_field :str%>
    dexterity<%= f.text_field :dex%>
    stamina<%= f.text_field :stam%>
  </div>
  <div class="socialattributes">
    charisma<%= f.text_field :cha%>
    manipulation<%= f.text_field :manip%>
    composure<%= f.text_field :comp%>
  </div>

<div class="explanationtext">
</div>
  <div class="mentalskills">
    Academics<%= f.text_field :academics%>
    Computer<%= f.text_field :computer%>
    Crafts<%= f.text_field :crafts%>
    Investigation<%= f.text_field :investigation%>
    Medicine<%= f.text_field :medicine%>
    Occult<%= f.text_field :occult%>
    Politics<%= f.text_field :politics%>
    Science <%= f.text_field :science%>
  </div>
  <div class="physicalskills">
    athletics<%= f.text_field :athletics%>
    brawl<%= f.text_field :brawl%>
    drive<%= f.text_field :drive%>
    firearms<%= f.text_field :firearms%>
    larceny<%= f.text_field :larceny%>
    stealth<%= f.text_field :stealth%>
    survival<%= f.text_field :survival%>
    weaponry<%= f.text_field :weaponry%>
  </div>
<div class="socialskills">
  animal ken<%= f.text_field :animalken%>
  empathy<%= f.text_field :empathy%>
  expression<%= f.text_field :expression%>
  intimidation<%= f.text_field :intimidation%>
  persuasion<%= f.text_field :persuasion%>
  socialize<%= f.text_field :socialize%>
  streetwise<%= f.text_field :streetwise%>
  subterfuge<%= f.text_field :subterfuge%>
</div>
  <%= f.text_field :meritlist%>
  <%= f.text_field :powerlist%>
  <%= f.text_field :experience%>

  <%= f.submit "Edit" %>

<% end %>

<%= link_to "Delete this character", character_path, method: :delete, data: {confirm: "Really delete this character?"} %>

app/views/characters/index.html.erb
<h1>characters</h1>
<a href="/login">Login</a><a href="/logout">Log out</a>
<ul>
  <% @characters.each do |character| %>
  <li>
    <div class="character">
      <h3><%= " #{character.name}"%> </h3>
      <h4><%=" by #{character.player.player_name}" %></h4>
      Name <p><%= character.name%></p>
      Intelligence<p><%= character.intel%> Wits <%= character.wits%>
      Resolve <%= character.res%></p>
      <p>Strength <%= character.str%>
        Dexterity <%= character.dex%>
      Stamina<%= character.stam%></p>
      <p>Charisma<%= character.cha%>
      Manipulation<%= character.manip%>
      Composure<%= character.comp%></p>
      Mental Skills
      <p>Academics<%= character.academics%>
      Computer<%= character.computer%>
      Crafts<%= character.crafts%>
      Investigation<%= character.investigation%>
      Medicine<%= character.medicine%>
      Occult<%= character.occult%>
      Politics<%= character.politics%>
      Science<%= character.science%></p>
      Physical Skills
      <p>Athletics<%= character.athletics%>
      Brawl<%= character.brawl%>
      Drive<%= character.drive%>
      Firearms<%= character.firearms%>
      Larceny<%= character.larceny%>
      Stealth<%= character.stealth%>
      Survival<%= character.survival%>
      Weaponry<%= character.weaponry%></p>
      Social Skills
      Animal Ken<p><%= character.animalken%>
      Empathy<p><%= character.empathy%>
      Expression<p><%= character.expression%>
      Intimidation<p><%= character.intimidation%>
      Persuasion<p><%= character.persuasion%>
      Socialize<p><%= character.socialize%>
      Streetwize<p><%= character.streetwise%>
      Subterfuge<p><%= character.subterfuge%>

      Misc. Stats
      Merits<p><%= character.meritlist%></p>
      Powers and supernatural abilities<p><%= character.powerlist%></p>
      XP<p><%= character.experience%></p>

      <% if character.player == current_player %>
        <%= link_to "Edit Your character" , edit_character_path(id: character.id) %>
      <% end %>
    </div>
  </li>
  <% end %>
</ul>

app/views/characters/new.html.erb
<%= form_for @character, url: "/characters" do |f| %>
Hey!   lets make a new character for you!
first things first, lets name your character.  try to pick something that fits the story of how the character came into being.
/<div class="name">
  <%= f.text_field :name%>
</div>
  next, lets talk about the three categories of stats. there are mental, physical and social attributes.
  each attribute starts at 1, because if you did not have these, your character wouldn't be able to interact with the world.
  you will have to assign priority between the different categories, and assign 5 points to the first,
  4 to the second, and 3 to the third.

  mental traits represent your character's internal mental capabilities.
  Intelligence represents brute mental capability.  Wits represents quick thinking and adaptability
  while resolve indicates "guts" or other forms of stick-to-itiveness
  <div class="mentalattributes">
    intelligence<%= f.text_field :intel%>
    Wits<%= f.text_field :wits%>
    resolve<%= f.text_field :res%>
    </div>
    next are the physical attributes, which represent your raw physical capability.
    strength represents pure muscle.  dexterity represents both manual dexterity and overall quickness.
    stamina represents how much punishment your body can take, either from exercise or taking a hit.
  <div class="physicalattributes">
    strength<%= f.text_field :str%>
    dexterity<%= f.text_field :dex%>
    stamina<%= f.text_field :stam%>
  </div>
  finally comes the social attributes.
  charisma represents your force of personality.
  manipulation represents your cleverness and ability to trick others.
  composure represents your ability to keep it together when faced with difficult social situations.
  <div class="socialattributes">
    charisma<%= f.text_field :cha%>
    manipulation<%= f.text_field :manip%>
    composure<%= f.text_field :comp%>
  </div>

<div class="explanationtext">
  Next let's assign skills.  skills are divided into the same three categories, mental, physical, and social.
  just as above, you would divide up your points between the three categories, except this time you have more.
  11 for the first, 7 for the second, 4 for the third.
</div>
  <div class="mentalskills">
    Academics<%= f.text_field :academics%>
    Computer<%= f.text_field :computer%>
    Crafts<%= f.text_field :crafts%>
    Investigation<%= f.text_field :investigation%>
    Medicine<%= f.text_field :medicine%>
    Occult<%= f.text_field :occult%>
    Politics<%= f.text_field :politics%>
    Science <%= f.text_field :science%>
  </div>
  <div class="physicalskills">
    athletics<%= f.text_field :athletics%>
    brawl<%= f.text_field :brawl%>
    drive<%= f.text_field :drive%>
    firearms<%= f.text_field :firearms%>
    larceny<%= f.text_field :larceny%>
    stealth<%= f.text_field :stealth%>
    survival<%= f.text_field :survival%>
    weaponry<%= f.text_field :weaponry%>
  </div>
<div class="socialskills">
  animal ken<%= f.text_field :animalken%>
  empathy<%= f.text_field :empathy%>
  expression<%= f.text_field :expression%>
  intimidation<%= f.text_field :intimidation%>
  persuasion<%= f.text_field :persuasion%>
  socialize<%= f.text_field :socialize%>
  streetwise<%= f.text_field :streetwise%>
  subterfuge<%= f.text_field :subterfuge%>
</div>

now, you have to choose seven levels of merits. consult your gamebooks to do that.
  <%= f.text_field :meritlist%>
please list any supernatural abilities, or morality traits your character has below.
  <%= f.text_field :powerlist%>
any experience you have earned should go here.
  <%= f.text_field :experience%>

  <%= f.submit "I'm DONE!" %>
Congratulations!
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Character Database</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/index.html.erb
<h1> Players </h1>

<ul>
  <% @players.each do |player| %>
    <li>
      <%= "player name: #{player.player_name}"%>
    </li>
  <% end %>
</ul>

app/views/players/new.html.erb
<h1>Create new Account</h1>

<%= form_for @player, url:"/players" do |f| %>

  Name: <%=f.text_field :player_name %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>

  <%= f.submit "Register" %>
<% end %>

app/views/stories/index.html.erb
<h1>Stories in our Collection</h1>

<ul>
  <% @story.each do |story| %>
  <li>
    <div class="story">
      <h3><%= " #{story.title}"%> </h3>
      <h4><%=" by #{story.player.player_name}" %></h4>
      <p><%= story.body %></p>
      <% if story.player == current_player %>
        <%= link_to "Edit Your story" , edit_story_path(id: story.id) %>
      <% end %>
    </div>
  </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<%= form_for @story, url: "/stories" do |f| %>

  Title: <%= f.text_field :title %>
  Body:  <%= f.text_area  :body  %>
  Max # of players? <%= f.text_field :maxplayers %>

  <%= f.submit "Start Telling Your Story" %>

<% end %>